title: WACD Resolutions
description: A five-year rolling window on resolutions adopted by Washington Association of Conservation District members.
theme: just-the-docs

# url: https://just-the-docs.github.io
url: https://tomsalzer.github.io/resolutions

# aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

layout: default
title: Home
nav_enabled: true

nav_links:
    - 2024 Resolutions: https://tomsalzer.github.io/resolutions/2024resolutions
    - 2023 Resolutions: https://tomsalzer.github.io/resolutions/2023resolutions
    - 2022 Resolutions: https://tomsalzer.github.io/resolutions/2022resolutions
    - 2021 Resolutions: https://tomsalzer.github.io/resolutions/2021resolutions
    

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true

